FROM python:3.10-slim

# setear workdir
WORKDIR /app

# dependencias del sistema
RUN apt-get update

# copia requirements e instala dependencias
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# copia código
COPY . /app